### PR TITLE
add a few target platforms, make adding platforms a little easier

### LINKED ISSUE #1: "Bad CPU type in executable" when running example
When I attempt to copy and past the readme.md example or run `deno run -A https://deno.land/x/systray/example/index.ts` I get the following error on MacOS.
image

```zsh
➜  urler deno run -A https://deno.land/x/systray/example/index.ts
Download ⠼ https://deno.land/x/systray/example/index.ts                                                                                                                                                                 Warning Implicitly using latest version (v0.2.2) for https://deno.land/x/systray/example/index.ts
error: Uncaught (in promise) Error: Bad CPU type in executable (os error 86)
    this._process = Deno.run({
                         ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at SysTray.run (https://deno.land/x/systray@v0.2.2/mod.ts:241:26)
    at SysTray.init (https://deno.land/x/systray@v0.2.2/mod.ts:273:12)

```

### PR DESCRIPTION
**Pull request by rummik**
This should resolve wobsoriano/deno-systray#1

### CODE REVIEW

**Comment by wobsoriano** [comment]
Thank you and sorry for the late response!

**Comment by Nedgeva** [comment]
Thank you guys very much for this merge.

**Comment by Nedgeva** [comment]
@wobsoriano any chance to see fresh builds?

**Comment by wobsoriano** [comment]
> @wobsoriano any chance to see fresh builds?

Tomorrow probably after work

**Pull request merged**
